import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const FROM_EMAIL = 'noreply@xpertaisolution.com'
const FROM_NAME = 'XpertAI Estimator'

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')
    if (!RESEND_API_KEY) {
      return json({ error: 'Email service not configured' }, 500)
    }

    const {
      to,
      clientName,
      companyName,
      replyTo,
      estimateNumber,
      projectType,
      totalQuote,
      daysOld,
      lang = 'en',
    } = await req.json()

    if (!to || !estimateNumber) {
      return json({ error: 'Missing required fields: to, estimateNumber' }, 400)
    }

    const isEs = lang === 'es'
    const displayName = companyName || FROM_NAME

    const projectDisplay = (projectType || '')
      .replace(/-/g, ' ')
      .replace(/\b\w/g, (c: string) => c.toUpperCase())

    const formattedTotal = new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(Number(totalQuote) || 0)

    const subject = isEs
      ? `Seguimiento: Estimación #${estimateNumber} — ${displayName}`
      : `Following up: Estimate #${estimateNumber} — ${displayName}`

    const greeting = isEs
      ? `Estimado/a ${escapeHtml(clientName || 'Cliente')}:`
      : `Hi ${escapeHtml(clientName || 'there')},`

    const daysNote = daysOld > 0
      ? (isEs
          ? `Hace ${daysOld} día${daysOld !== 1 ? 's' : ''} enviamos una estimación para su proyecto.`
          : `${daysOld} day${daysOld !== 1 ? 's' : ''} ago we sent you an estimate for your project.`)
      : (isEs ? 'Recientemente enviamos una estimación para su proyecto.' : 'We recently sent you an estimate for your project.')

    const body1 = isEs
      ? 'Queríamos hacer seguimiento y verificar si tiene alguna pregunta o si hay algo en lo que podamos ayudarle antes de tomar una decisión.'
      : "We wanted to follow up and check if you have any questions or if there's anything we can help clarify before you make a decision."

    const body2 = isEs
      ? 'Estamos aquí para ayudarle. No dude en responder a este correo o llamarnos directamente.'
      : "We're here to help. Feel free to reply to this email or give us a call directly."

    const estimateLabel = isEs ? 'ESTIMACIÓN' : 'ESTIMATE'
    const projectLabel = isEs ? 'PROYECTO' : 'PROJECT'
    const totalLabel = isEs ? 'TOTAL' : 'TOTAL'
    const footerNote = isEs ? 'Generado por XpertAI Estimator' : 'Generated by XpertAI Estimator'

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#333">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%">
        <!-- Header -->
        <tr>
          <td style="background:#3f36cb;padding:28px 32px;border-radius:12px 12px 0 0">
            <p style="margin:0;font-size:22px;font-weight:bold;color:#fff">${escapeHtml(displayName)}</p>
            <p style="margin:6px 0 0;font-size:13px;color:rgba(255,255,255,0.75)">${isEs ? 'Correo de seguimiento' : 'Follow-up message'}</p>
          </td>
        </tr>
        <!-- Body -->
        <tr>
          <td style="background:#fff;padding:32px;border-left:1px solid #e5e7eb;border-right:1px solid #e5e7eb">
            <p style="margin:0 0 16px;font-size:15px">${greeting}</p>
            <p style="margin:0 0 16px;font-size:14px;color:#555;line-height:1.6">${daysNote}</p>
            <!-- Summary card -->
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f9ff;border:1px solid #e0e1ff;border-radius:10px;margin-bottom:24px">
              <tr>
                <td style="padding:20px 24px">
                  <p style="margin:0;font-size:11px;font-weight:bold;color:#6366f1;letter-spacing:0.08em">${estimateLabel}</p>
                  <p style="margin:4px 0 16px;font-size:18px;font-weight:bold;color:#1f2937">#${escapeHtml(estimateNumber || '')}</p>
                  <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td width="50%" style="vertical-align:top">
                        <p style="margin:0;font-size:11px;font-weight:bold;color:#6366f1;letter-spacing:0.08em">${projectLabel}</p>
                        <p style="margin:4px 0 0;font-size:14px;font-weight:600;color:#1f2937">${escapeHtml(projectDisplay)}</p>
                      </td>
                      <td width="50%" style="vertical-align:top;text-align:right">
                        <p style="margin:0;font-size:11px;font-weight:bold;color:#6366f1;letter-spacing:0.08em">${totalLabel}</p>
                        <p style="margin:4px 0 0;font-size:22px;font-weight:bold;color:#3f36cb">${formattedTotal}</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <p style="margin:0 0 16px;font-size:14px;color:#555;line-height:1.6">${body1}</p>
            <p style="margin:0 0 24px;font-size:14px;color:#555;line-height:1.6">${body2}</p>
          </td>
        </tr>
        <!-- Footer -->
        <tr>
          <td style="background:#f9fafb;padding:16px 32px;text-align:center;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
            <p style="margin:0;font-size:12px;color:#9ca3af">${escapeHtml(displayName)} &middot; ${footerNote}</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`

    const emailPayload: Record<string, unknown> = {
      from: `${displayName} <${FROM_EMAIL}>`,
      to: [to],
      subject,
      html,
    }

    if (replyTo) emailPayload.reply_to = replyTo

    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(emailPayload),
    })

    const resendData = await resendRes.json()
    return json(resendData, resendRes.ok ? 200 : 400)
  } catch (err) {
    return json({ error: String(err) }, 500)
  }
})

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
