import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'
import { encodeBase64 } from 'https://deno.land/std@0.224.0/encoding/base64.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const FROM_EMAIL = 'noreply@xpertaisolution.com'
const FROM_NAME = 'XpertAI Estimator'

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY')
    if (!RESEND_API_KEY) {
      return json({ error: 'Email service not configured' }, 500)
    }

    const {
      to,
      companyName,
      replyTo,
      reportTab,
      reportRange,
      signedUrl,
      filename,
      lang = 'en',
    } = await req.json()

    if (!to || !signedUrl) {
      return json({ error: 'Missing required fields: to, signedUrl' }, 400)
    }

    const pdfRes = await fetch(signedUrl)
    if (!pdfRes.ok) {
      return json({ error: `Failed to fetch PDF: ${pdfRes.status}` }, 500)
    }
    const pdfBuffer = await pdfRes.arrayBuffer()
    const pdfBase64 = encodeBase64(new Uint8Array(pdfBuffer))

    const isEs = lang === 'es'
    const displayName = companyName || FROM_NAME

    const tabLabels: Record<string, string> = {
      overview: isEs ? 'Resumen' : 'Overview',
      payments: isEs ? 'Pagos' : 'Payments',
      pipeline: isEs ? 'Pipeline' : 'Pipeline',
      projects: isEs ? 'Proyectos' : 'Projects',
      aging: isEs ? 'Vencidos' : 'Aging',
    }
    const rangeLabels: Record<string, string> = {
      thisMonth: isEs ? 'Este Mes' : 'This Month',
      last3: isEs ? 'Últimos 3 Meses' : 'Last 3 Months',
      thisYear: isEs ? 'Este Año' : 'This Year',
      allTime: isEs ? 'Todo el Tiempo' : 'All Time',
    }

    const tabLabel = tabLabels[reportTab] ?? reportTab
    const rangeLabel = rangeLabels[reportRange] ?? reportRange

    const subject = isEs
      ? `Reporte ${tabLabel} — ${rangeLabel} | ${displayName}`
      : `${tabLabel} Report — ${rangeLabel} | ${displayName}`

    const intro = isEs
      ? `Adjunto encontrará el reporte <strong>${tabLabel}</strong> correspondiente al período <strong>${rangeLabel}</strong>.`
      : `Please find attached the <strong>${tabLabel}</strong> report for <strong>${rangeLabel}</strong>.`

    const footer = isEs
      ? 'Generado por XpertAI Estimator'
      : 'Generated by XpertAI Estimator'

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif;color:#333">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:32px 16px">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%">
        <tr>
          <td style="background:#3f36cb;padding:28px 32px;border-radius:12px 12px 0 0">
            <p style="margin:0;font-size:22px;font-weight:bold;color:#fff">${escapeHtml(displayName)}</p>
            <p style="margin:6px 0 0;font-size:14px;color:rgba(255,255,255,0.8)">${escapeHtml(subject)}</p>
          </td>
        </tr>
        <tr>
          <td style="background:#fff;padding:32px;border-left:1px solid #e5e7eb;border-right:1px solid #e5e7eb">
            <p style="margin:0 0 20px;font-size:15px;color:#374151;line-height:1.6">${intro}</p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f9ff;border:1px solid #e0e1ff;border-radius:10px;margin-bottom:24px">
              <tr>
                <td style="padding:20px 24px">
                  <p style="margin:0;font-size:11px;font-weight:bold;color:#6366f1;letter-spacing:0.08em">${isEs ? 'REPORTE' : 'REPORT'}</p>
                  <p style="margin:4px 0 12px;font-size:18px;font-weight:bold;color:#1f2937">${escapeHtml(tabLabel)}</p>
                  <p style="margin:0;font-size:11px;font-weight:bold;color:#6366f1;letter-spacing:0.08em">${isEs ? 'PERÍODO' : 'PERIOD'}</p>
                  <p style="margin:4px 0 0;font-size:16px;font-weight:bold;color:#3f36cb">${escapeHtml(rangeLabel)}</p>
                </td>
              </tr>
            </table>
            <p style="margin:0;font-size:13px;color:#9ca3af">
              ${isEs ? 'El PDF completo está adjunto.' : 'The full PDF report is attached.'}
            </p>
          </td>
        </tr>
        <tr>
          <td style="background:#f9fafb;padding:16px 32px;text-align:center;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 12px 12px">
            <p style="margin:0;font-size:12px;color:#9ca3af">${escapeHtml(displayName)} &middot; ${footer}</p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`

    const emailPayload: Record<string, unknown> = {
      from: `${displayName} <${FROM_EMAIL}>`,
      to: [to],
      subject,
      html,
      attachments: [{
        filename: filename || `Report_${reportTab}_${reportRange}.pdf`,
        content: pdfBase64,
      }],
    }

    if (replyTo) emailPayload.reply_to = replyTo

    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(emailPayload),
    })

    const resendData = await resendRes.json()
    return json(resendData, resendRes.ok ? 200 : 400)
  } catch (err) {
    return json({ error: String(err) }, 500)
  }
})

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
